# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e88af1197ef706959f03cd3bd7abc3907b3bc6079a0fe454cd6bc6fdde0e5661b2faffdd4f22b25108236913982f57078cc71d398aaf9fc8e16fc55053dedd23

test:
  secret_key_base: 6f6bf942118ab45288b2b2e729be9a294b1deaea38939fb92e747bf121d4e8c18c65145eda0052010401731109c4a1d6b19b2451559480da79a3fbfc1b4f8c81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
